services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sigma
      - POSTGRES_USER=sigma
      - POSTGRES_DB=sigma

volumes:
  postgres: { }