#!/bin/sh

# Set up application for the first time after cloning, or set it back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."
script/bootstrap

if [ ! -f .env.local ]; then
  cp .env.example .env
fi

if [ -d node_modules ]; then
  echo "==> Cleaning installed dependencies..."
  git clean -x --force -- node_modules
fi
